name: Check

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Setup latest go 1.18 version
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.x

      - name: Build CLI
        run: go build -o mrinjamulcf-cli ./cmd/...

      - name: Check the records
        run: |
          go version
          ./mrinjamulcf-cli fmt --check
