name: DNS Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    if: github.repository == 'mrinjamul/mrinjamul-main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Setup latest go 1.18 version
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.x

      - name: Build CLI
        run: go build -o flareship ./cmd/...

      - name: Sync DNS --dry-run
        env:
          FLARESHIP_DOMAINS: ${{ secrets.FLARESHIP_DOMAINS }}
          FLARESHIP_CF_TOKENS: ${{ secrets.FLARESHIP_CF_TOKENS }}
          FLARESHIP_ZONE_IDS: ${{ secrets.FLARESHIP_ZONE_IDS }}
          FLARESHIP_RECORD_FILES: ${{ secrets.FLARESHIP_RECORD_FILES }}
          FLARESHIP_RESTRICTED_FILES: ${{ secrets.FLARESHIP_RESTRICTED_FILES }}
          FLARESHIP_ALLOWED_TYPES: ${{ secrets.FLARESHIP_ALLOWED_TYPES }}
        run: |
          go version
          ./flareship sync --dry-run

      - name: Sync DNS
        env:
          FLARESHIP_DOMAINS: ${{ secrets.FLARESHIP_DOMAINS }}
          FLARESHIP_CF_TOKENS: ${{ secrets.FLARESHIP_CF_TOKENS }}
          FLARESHIP_ZONE_IDS: ${{ secrets.FLARESHIP_ZONE_IDS }}
          FLARESHIP_RECORD_FILES: ${{ secrets.FLARESHIP_RECORD_FILES }}
          FLARESHIP_RESTRICTED_FILES: ${{ secrets.FLARESHIP_RESTRICTED_FILES }}
          FLARESHIP_ALLOWED_TYPES: ${{ secrets.FLARESHIP_ALLOWED_TYPES }}
        run: |
          go version
          ./flareship sync
