name: DNS Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    if: github.repository == 'mrinjamul/mrinjamul-main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Setup latest go 1.18 version
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.x

      - name: Build CLI
        run: go build -o flareship ./cmd/...

      - name: Sync DNS --dry-run
        env:
          CF_ZID: ${{ secrets.CF_ZID }}
          CF_TOK: ${{ secrets.CF_TOK }}
        run: |
          go version
          ./flareship sync --dry-run

      - name: Sync DNS
        env:
          CF_ZID: ${{ secrets.CF_ZID }}
          CF_TOK: ${{ secrets.CF_TOK }}
        run: |
          go version
          ./flareship sync
